export interface QuizQuestion {
  id: number;
  categoria: string;
  pergunta: string;
  opcoes: string[]; // 4 alternativas
  correta: number; // 0, 1, 2 ou 3
  curiosidade: string;
}

export const quizQuestions: QuizQuestion[] = [
  {
    id: 1,
    categoria: 'Ciência & Espaço',
    pergunta: 'Qual é o planeta mais próximo do Sol no Sistema Solar?',
    opcoes: ['Vênus', 'Mercúrio', 'Marte', 'Terra'],
    correta: 1,
    curiosidade: 'Apesar de Mercúrio ser o mais próximo do Sol, Vênus é o planeta mais quente por causa do efeito estufa extremo!',
  },
  {
    id: 2,
    categoria: 'Geografia do Brasil',
    pergunta: 'Qual é o maior estado brasileiro em extensão territorial?',
    opcoes: ['Mato Grosso', 'Minas Gerais', 'Amazonas', 'Bahia'],
    correta: 2,
    curiosidade: 'O Amazonas tem mais de 1,5 milhão de km², sendo maior que países inteiros como França, Espanha e Alemanha somados!',
  },
  {
    id: 3,
    categoria: 'História & Cultura',
    pergunta: 'Em que ano o Brasil proclamou sua Independência de Portugal?',
    opcoes: ['1808', '1822', '1889', '1500'],
    correta: 1,
    curiosidade: 'A Independência aconteceu no dia 7 de setembro de 1822, às margens do riacho Ipiranga em São Paulo.',
  },
  {
    id: 4,
    categoria: 'Futebol & Esportes',
    pergunta: 'Qual jogador foi eleito o melhor do mundo 8 vezes pela FIFA/Bola de Ouro?',
    opcoes: ['Cristiano Ronaldo', 'Pelé', 'Lionel Messi', 'Ronaldinho Gaúcho'],
    correta: 2,
    curiosidade: 'Lionel Messi detém o recorde histórico com 8 Bolas de Ouro conquistadas ao longo da carreira.',
  },
  {
    id: 5,
    categoria: 'Cultura Pop & Cinema',
    pergunta: 'Qual é o nome do criador do Homem-Aranha, Homem de Ferro e Thor na Marvel?',
    opcoes: ['Stan Lee', 'Bob Kane', 'Jack Kirby', 'Walt Disney'],
    correta: 0,
    curiosidade: 'Stan Lee co-criou a maioria dos super-heróis lendários da Marvel nos anos 1960 junto com Jack Kirby e Steve Ditko.',
  },
  {
    id: 6,
    categoria: 'Biologia & Animais',
    pergunta: 'Qual é o maior animal vivo que já existiu no planeta Terra?',
    opcoes: ['Tubarão Megalodonte', 'Elefante Africano', 'Baleia-Azul', 'Tiranossauro Rex'],
    correta: 2,
    curiosidade: 'A Baleia-Azul pode atingir até 30 metros de comprimento e pesar quase 200 toneladas — superando qualquer dinossauro já descoberto!',
  },
  {
    id: 7,
    categoria: 'Memes & Internet',
    pergunta: 'Qual meme brasileiro ficou famoso com o bordão "Eita, Giovana! O forninho caiu"?',
    opcoes: ['Menina do Bambu', 'Menina do Forninho', 'Grávida de Taubaté', 'Gretchen'],
    correta: 1,
    curiosidade: 'O vídeo viralizou em 2014, quando a prima filmava Giovana dançando até derrubar o forno elétrico da cozinha!',
  },
  {
    id: 8,
    categoria: 'Ciência & Física',
    pergunta: 'Qual é a velocidade aproximada da luz no vácuo?',
    opcoes: ['300.000 km/s', '150.000 km/s', '1.000.000 km/s', '30.000 km/s'],
    correta: 0,
    curiosidade: 'A luz viaja a cerca de 299.792 km/s. Com essa velocidade, daria mais de 7 voltas completas na Terra em apenas um segundo!',
  },
  {
    id: 9,
    categoria: 'Geografia Mundial',
    pergunta: 'Qual é o rio mais extenso do mundo?',
    opcoes: ['Rio Nilo', 'Rio Amazonas', 'Rio Mississippi', 'Rio Yangtzé'],
    correta: 1,
    curiosidade: 'Medições cartográficas modernas confirmam o Rio Amazonas como o mais longo do mundo, com quase 7.000 km de extensão!',
  },
  {
    id: 10,
    categoria: 'Música & Artes',
    pergunta: 'Qual cantora brasileira alcançou o Top 1 Global do Spotify com o hit "Envolver"?',
    opcoes: ['Ivete Sangalo', 'Luísa Sonza', 'Anitta', 'Ludmilla'],
    correta: 2,
    curiosidade: 'Em março de 2022, Anitta se tornou a primeira artista brasileira e latina solo a alcançar o primeiro lugar mundial do Spotify.',
  },
  {
    id: 11,
    categoria: 'Cultura Pop & Séries',
    pergunta: 'Na série "Breaking Bad", qual é o pseudônimo que Walter White usa no submundo do crime?',
    opcoes: ['Scarface', 'Heisenberg', 'Gus Fring', 'Saul Goodman'],
    correta: 1,
    curiosidade: 'O nome Heisenberg foi uma homenagem de Walter White ao famoso físico alemão Werner Heisenberg, criador do Princípio da Incerteza.',
  },
  {
    id: 12,
    categoria: 'Futebol Brasileiro',
    pergunta: 'Qual clube brasileiro venceu o primeiro Mundial de Clubes organizado pela FIFA no ano 2000?',
    opcoes: ['São Paulo', 'Corinthians', 'Vasco da Gama', 'Flamengo'],
    correta: 1,
    curiosidade: 'O Corinthians foi o primeiro campeão mundial da FIFA no Maracanã, vencendo o Vasco na disputa de pênaltis.',
  },
  {
    id: 13,
    categoria: 'Tecnologia',
    pergunta: 'Quem foi o fundador principal da Microsoft junto com Paul Allen?',
    opcoes: ['Steve Jobs', 'Bill Gates', 'Elon Musk', 'Mark Zuckerberg'],
    correta: 1,
    curiosidade: 'Bill Gates e Paul Allen fundaram a Microsoft em 1975, criando o sistema MS-DOS e depois o Windows.',
  },
  {
    id: 14,
    categoria: 'Química & Elementos',
    pergunta: 'Qual é o símbolo químico do elemento Ouro na tabela periódica?',
    opcoes: ['Or', 'Au', 'Ag', 'Fe'],
    correta: 1,
    curiosidade: 'O símbolo "Au" vem do latim "Aurum", que significa "brilhante" ou "resplandecente da aurora".',
  },
  {
    id: 15,
    categoria: 'Cinema & Animação',
    pergunta: 'Qual foi o primeiro longa-metragem animado totalmente feito por computador na história?',
    opcoes: ['Shrek', 'Toy Story', 'Monstros S.A.', 'Vida de Inseto'],
    correta: 1,
    curiosidade: 'Toy Story foi lançado pela Pixar em 1995 e revolucionou para sempre a indústria cinematográfica de animação.',
  },
  {
    id: 16,
    categoria: 'História Geral',
    pergunta: 'Em que país foi construído o monumento histórico do Coliseu?',
    opcoes: ['Grécia', 'França', 'Itália', 'Egito'],
    correta: 2,
    curiosidade: 'O Coliseu fica em Roma, na Itália, e foi inaugurado no ano 80 d.C., acolhendo até 50 mil espectadores para combates de gladiadores.',
  },
  {
    id: 17,
    categoria: 'Cultura Geek & Games',
    pergunta: 'No jogo Minecraft, qual bloco é necessário para construir o portal que leva ao Nether?',
    opcoes: ['Bedrock', 'Obsidiana', 'Redstone', 'Diamante'],
    correta: 1,
    curiosidade: 'São necessários no mínimo 10 blocos de obsidiana e uma pederneira (isqueiro) para acender o portal do Nether.',
  },
  {
    id: 18,
    categoria: 'Corpo Humano',
    pergunta: 'Qual é o maior órgão do corpo humano?',
    opcoes: ['Fígado', 'Pele', 'Intestino', 'Pulmão'],
    correta: 1,
    curiosidade: 'A pele é o maior órgão humano, pesando cerca de 4 kg e cobrindo uma área de aproximadamente 2 metros quadrados em um adulto.',
  },
  {
    id: 19,
    categoria: 'Literatura & Linguagem',
    pergunta: 'Quem é o autor do clássico da literatura brasileira "Dom Casmurro"?',
    opcoes: ['Machado de Assis', 'José de Alencar', 'Clarice Lispector', 'Monteiro Lobato'],
    correta: 0,
    curiosidade: 'Machado de Assis publicou Dom Casmurro em 1899, eternizando a maior dúvida da literatura: Capitu traiu ou não traiu Bentinho?',
  },
  {
    id: 20,
    categoria: 'Geografia Mundial',
    pergunta: 'Qual é o país com o maior número de habitantes no mundo atualmente?',
    opcoes: ['China', 'Índia', 'Estados Unidos', 'Indonésia'],
    correta: 1,
    curiosidade: 'Em 2023, a Índia ultrapassou a China e se tornou oficialmente o país mais populoso do mundo, com mais de 1,4 bilhão de pessoas.',
  },
  {
    id: 21,
    categoria: 'Astronomia',
    pergunta: 'Quantos minutos a luz do Sol leva para chegar até a Terra?',
    opcoes: ['Aproximadamente 8 minutos', 'Aproximadamente 1 segundo', 'Aproximadamente 1 hora', 'Aproximadamente 30 segundos'],
    correta: 0,
    curiosidade: 'A luz do Sol leva exatos 8 minutos e 20 segundos para percorrer os 150 milhões de quilômetros até a Terra!',
  },
  {
    id: 22,
    categoria: 'Cultura Pop & Anime',
    pergunta: 'No anime Dragon Ball Z, qual é a transformação lendária que Goku atinge na luta contra Freeza?',
    opcoes: ['Super Saiyajin', 'Instinto Superior', 'Super Saiyajin 3', 'Kaioken 100x'],
    correta: 0,
    curiosidade: 'Goku se transformou em Super Saiyajin pela primeira vez em Namekusei após Freeza assassinar Kuririn.',
  },
  {
    id: 23,
    categoria: 'Gastronomia',
    pergunta: 'Qual estado brasileiro é mundialmente conhecido pelo autêntico Pão de Queijo e Feijão Tropeiro?',
    opcoes: ['Rio Grande do Sul', 'Minas Gerais', 'Goiás', 'Paraná'],
    correta: 1,
    curiosidade: 'Minas Gerais é o berço do pão de queijo tradicional, feito com polvilho doce/azedo e queijo curado da Canastra.',
  },
  {
    id: 24,
    categoria: 'Futebol Internacional',
    pergunta: 'Qual seleção de futebol venceu a Copa do Mundo de 2022 no Catar?',
    opcoes: ['França', 'Brasil', 'Argentina', 'Croácia'],
    correta: 2,
    curiosidade: 'A Argentina conquistou seu tricampeonato mundial em 2022 após uma das maiores finais da história contra a França nos pênaltis.',
  },
  {
    id: 25,
    categoria: 'Curiosidades & Natureza',
    pergunta: 'Quantos corações tem um polvo?',
    opcoes: ['1 coração', '2 corações', '3 corações', '4 corações'],
    correta: 2,
    curiosidade: 'Os polvos têm 3 corações: dois bombeiam sangue para as brânquias e o terceiro bombeia para o resto do corpo. Além disso, seu sangue é azul!',
  },
  {
    id: 26,
    categoria: 'Música Brasileira',
    pergunta: 'Quem é conhecido no Brasil como o "Rei do Rock Brasileiro" e fundador do Barão Vermelho?',
    opcoes: ['Raul Seixas', 'Renato Russo', 'Cazuza', 'Chorão'],
    correta: 2,
    curiosidade: 'Cazuza foi o icônico vocalista do Barão Vermelho nos anos 80 antes de seguir em sua carreira solo brilhante.',
  },
  {
    id: 27,
    categoria: 'Cinema & Franquias',
    pergunta: 'Em "Star Wars", qual é a famosa frase que Darth Vader diz a Luke Skywalker?',
    opcoes: ['Luke, eu sou seu pai', 'Não, eu sou seu pai', 'Eu sou seu mestre', 'Junte-se ao lado sombrio'],
    correta: 1,
    curiosidade: 'O efeito Mandela faz muitos acharem que é "Luke, eu sou seu pai", mas a fala exata de Darth Vader em O Império Contra-Ataca é: "Não, eu sou seu pai".',
  },
  {
    id: 28,
    categoria: 'Matemática & Números',
    pergunta: 'Qual é o valor aproximado do número Pi (π)?',
    opcoes: ['2,71', '3,14', '1,61', '4,20'],
    correta: 1,
    curiosidade: 'Pi é uma constante matemática infinita e irracional que representa a relação entre o perímetro de qualquer círculo e seu diâmetro.',
  },
  {
    id: 29,
    categoria: 'Tecnologia & Redes',
    pergunta: 'Qual aplicativo de mensagens foi criado pelos ex-funcionários do Yahoo Jan Koum e Brian Acton em 2009?',
    opcoes: ['Telegram', 'WhatsApp', 'Discord', 'Signal'],
    correta: 1,
    curiosidade: 'O WhatsApp foi vendido para o Facebook (Meta) em 2014 pela bagatela de 19 bilhões de dólares!',
  },
  {
    id: 30,
    categoria: 'Geografia do Brasil',
    pergunta: 'Qual é a capital oficial do Brasil?',
    opcoes: ['Rio de Janeiro', 'São Paulo', 'Brasília', 'Salvador'],
    correta: 2,
    curiosidade: 'Brasília foi inaugurada em 21 de abril de 1960 pelo presidente Juscelino Kubitschek, substituindo o Rio de Janeiro como capital.',
  },
  {
    id: 31,
    categoria: 'Cultura Pop & Quadrinhos',
    pergunta: 'Qual herói dos quadrinhos vive na cidade fictícia de Gotham City?',
    opcoes: ['Superman', 'Batman', 'Flash', 'Homem de Ferro'],
    correta: 1,
    curiosidade: 'Batman patrulha Gotham City desde sua estreia na revista Detective Comics #27 em maio de 1939.',
  },
  {
    id: 32,
    categoria: 'Ciência & Biologia',
    pergunta: 'Qual gás os humanos inalam para respirar e qual gás exalam principalmente?',
    opcoes: ['Inalam Oxigênio e exalam Gás Carbônico', 'Inalam Nitrogênio e exalam Hélio', 'Inalam Gás Carbônico e exalam Oxigênio', 'Inalam Hidrogênio e exalam Oxigênio'],
    correta: 0,
    curiosidade: 'Nossas células usam oxigênio (O₂) para gerar energia celular e eliminam dióxido de carbono (CO₂) através da respiração pulmonar.',
  },
  {
    id: 33,
    categoria: 'Jogos & Videogames',
    pergunta: 'Qual é o nome do encanador italiano mais famoso dos videogames?',
    opcoes: ['Luigi', 'Sonic', 'Mario', 'Wario'],
    correta: 2,
    curiosidade: 'Antes de ter seu próprio jogo, Mario se chamava "Jumpman" no jogo clássico Donkey Kong de 1981!',
  },
  {
    id: 34,
    categoria: 'História do Brasil',
    pergunta: 'Quem assinou a Lei Áurea em 1888 que aboliu a escravidão no Brasil?',
    opcoes: ['Dom Pedro II', 'Princesa Isabel', 'Tiradentes', 'Deodoro da Fonseca'],
    correta: 1,
    curiosidade: 'A Princesa Isabel assinou a Lei Áurea em 13 de maio de 1888 enquanto exercia a regência do Império do Brasil.',
  },
  {
    id: 35,
    categoria: 'Futebol',
    pergunta: 'Quantas Copas do Mundo a Seleção Brasileira masculina de futebol já venceu?',
    opcoes: ['4 Copas', '5 Copas', '6 Copas', '3 Copas'],
    correta: 1,
    curiosidade: 'O Brasil é o único país pentacampeão mundial (1958, 1962, 1970, 1994 e 2002).',
  },
  {
    id: 36,
    categoria: 'Cultura Pop & Cinema',
    pergunta: 'Em "O Senhor dos Anéis", qual criatura repete obsessivamente a frase "Meu Precioso"?',
    opcoes: ['Frodo', 'Gollum', 'Gandalf', 'Legolas'],
    correta: 1,
    curiosidade: 'Gollum, originalmente um hobbit chamado Sméagol, foi corrompido durante séculos pelo poder maligno do Um Anel.',
  },
  {
    id: 37,
    categoria: 'Mundo Animal',
    pergunta: 'Qual ave é conhecida por não voar e ser uma excelente nadadora no Polo Sul e regiões geladas?',
    opcoes: ['Avestruz', 'Pinguim', 'Gaivota', 'Kiwi'],
    correta: 1,
    curiosidade: 'As asas dos pinguins evoluíram como nadadeiras super hidrodinâmicas, permitindo mergulhos de até 500 metros de profundidade.',
  },
  {
    id: 38,
    categoria: 'Cultura Geek & Séries',
    pergunta: 'Na série Stranger Things, como se chama a dimensão sombria e paralela?',
    opcoes: ['Mundo Invertido', 'Limbo', 'Submundo', 'Terras Sombrias'],
    correta: 0,
    curiosidade: 'O Mundo Invertido (Upside Down) reflete a mesma estrutura de Hawkins, mas coberta por vinhas e esporos tóxicos.',
  },
  {
    id: 39,
    categoria: 'Ciência & Saúde',
    pergunta: 'Quantos ossos tem o esqueleto de um ser humano adulto em média?',
    opcoes: ['150 ossos', '206 ossos', '300 ossos', '280 ossos'],
    correta: 1,
    curiosidade: 'Bebês nascem com cerca de 270 a 300 ossos, mas muitos se fundem durante o crescimento, resultando em 206 ossos no adulto.',
  },
  {
    id: 40,
    categoria: 'Música Internacional',
    pergunta: 'Qual banda britânica lendária lançou os álbuns "Abbey Road" e "Sgt. Pepper\'s"?',
    opcoes: ['Queen', 'The Rolling Stones', 'The Beatles', 'Pink Floyd'],
    correta: 2,
    curiosidade: 'The Beatles é a banda mais vendida da história da música com mais de 600 milhões de discos comercializados mundialmente.',
  },
  {
    id: 41,
    categoria: 'Geografia & Maravilhas',
    pergunta: 'Em qual país ficam localizadas as famosas Pirâmides de Gizé?',
    opcoes: ['México', 'Egito', 'Peru', 'Jordânia'],
    correta: 1,
    curiosidade: 'A Grande Pirâmide de Gizé foi construída há mais de 4.500 anos e é a única das Sete Maravilhas do Mundo Antigo ainda em pé.',
  },
  {
    id: 42,
    categoria: 'Carros & Engenharia',
    pergunta: 'Qual montadora italiana fabrica os famosos carros esportivos com o cavalo empinado no logotipo?',
    opcoes: ['Lamborghini', 'Ferrari', 'Maserati', 'Alfa Romeo'],
    correta: 1,
    curiosidade: 'Enzo Ferrari adotou o "Cavallino Rampante" em homenagem ao herói aviador italiano da 1ª Guerra Mundial Francesco Baracca.',
  },
  {
    id: 43,
    categoria: 'Cultura Pop & Games',
    pergunta: 'Qual franquia de jogos é estrelada pelo guerreiro espartano Kratos?',
    opcoes: ['Assassin\'s Creed', 'God of War', 'Dark Souls', 'Devil May Cry'],
    correta: 1,
    curiosidade: 'Kratos estreou no PlayStation 2 em 2005 e mais tarde migrou da mitologia grega para a mitologia nórdica com seu filho Atreus.',
  },
  {
    id: 44,
    categoria: 'Química & Substâncias',
    pergunta: 'Qual é a fórmula molecular da água?',
    opcoes: ['CO2', 'NaCl', 'H2O', 'CH4'],
    correta: 2,
    curiosidade: 'Cada molécula de água é composta por 2 átomos de hidrogênio e 1 átomo de oxigênio unidos por ligações covalentes.',
  },
  {
    id: 45,
    categoria: 'Memes Brasileiros',
    pergunta: 'Quem ficou famosa na internet com a frase "Não sei se sou bonita ou se sou um meme"?',
    opcoes: ['Inês Brasil', 'Blogueirinha', 'Gkay', 'Tulla Luana'],
    correta: 0,
    curiosidade: 'Inês Brasil conquistou a internet após seu vídeo de inscrição para o Big Brother Brasil vazar em 2012 e se tornar um fenômeno atemporal.',
  },
  {
    id: 46,
    categoria: 'Astronomia & Universo',
    pergunta: 'Qual é a galáxia espiral mais próxima da nossa Via Láctea?',
    opcoes: ['Galáxia de Andrômeda', 'Galáxia do Sombrero', 'Galáxia do Triângulo', 'Centaurus A'],
    correta: 0,
    curiosidade: 'Andrômeda está a 2,5 milhões de anos-luz da Terra e colidirá com a Via Láctea daqui a cerca de 4,5 bilhões de anos.',
  },
  {
    id: 47,
    categoria: 'Economia & Moedas',
    pergunta: 'Em que ano a moeda oficial do Brasil passou a ser o Real (R$)?',
    opcoes: ['1985', '1994', '2000', '1990'],
    correta: 1,
    curiosidade: 'O Plano Real entrou em vigor no dia 1º de julho de 1994, estabilizando a hiperinflação histórica que assolava o país.',
  },
  {
    id: 48,
    categoria: 'Mitologia',
    pergunta: 'Na mitologia nórdica, qual deus empunha o martelo mágico Mjolnir?',
    opcoes: ['Odin', 'Loki', 'Thor', 'Freyr'],
    correta: 2,
    curiosidade: 'Mjolnir foi forjado pelos anões ferreiros Brokk e Eitri e era capaz de nivelar montanhas inteiras com um único golpe.',
  },
  {
    id: 49,
    categoria: 'Cultura Pop & Harry Potter',
    pergunta: 'Em Hogwarts, para qual casa o Chapéu Seletor envia os alunos conhecidos pela coragem e bravura?',
    opcoes: ['Sonserina', 'Corvinal', 'Lufa-Lufa', 'Grifinória'],
    correta: 3,
    curiosidade: 'Grifinória tem como cores o vermelho e o dourado e como símbolo o leão. Seus membros mais famosos são Harry, Rony e Hermione.',
  },
  {
    id: 50,
    categoria: 'Curiosidades do Mundo',
    pergunta: 'Qual país inventou o papel, a pólvora, a bússola e a prensa tipográfica móvel?',
    opcoes: ['Japão', 'China', 'Índia', 'Grécia'],
    correta: 1,
    curiosidade: 'Essas quatro grandes invenções históricas foram criadas na China Antiga séculos antes de chegarem ao continente europeu.',
  },
];
